import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { Cal_Sans } from "next/font/google";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

const calSans = Cal_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cal-sans",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html
  lang="en"
  className={`${geist.variable} ${calSans.variable}`}
>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
